### ISSUE TITLE
Angular 15 Ivy Engine

### ISSUE THREAD

**Issue by SirSkizo** [alberthaff/ngx-papaparse#113]
This is just a suggestion:

After updating an Angular Project from `v14` to `v15` I get the following warning:

```bash
Processing legacy "View Engine" libraries:
- ngx-papaparse [es2015/esm2015] (https://github.com/alberthaff/ngx-papaparse)
Encourage the library authors to publish an Ivy distribution.
```

As detailed [here](https://update.angular.io/?l=3&v=14.0-15.0), Ivy is going to be the only available Engine for Angular. 

> In your application's tsconfig.json file, remove enableIvy. In v15, Ivy is the only rendering engine so enableIvy is not required.

It is possible that in future versions of Angular this will cause some errors.

**Comment by SamScholefield-open200** [comment]
When updating did you manually uninstall your current version of papaparse and reinstall using `npm install ngx-papaparse@7 --save`?

Fresh install with 15 and I see no legacy engine warnings...

**Comment by alberthaff** [comment]
@SirSkizo Please provide an exact angular and library version.

**Comment by alberthaff** [comment]
It's stated in the beginning of the readme on GH, NPM and on the docs website.
