### ISSUE TITLE
'comments' in interface PapaParseConfig has type 'false'

### ISSUE THREAD

**Issue by RozennK** [Alberthaff/ngx-papaparse#13]
It sounds, given the documentation for Papa Parse, that the 'comments' property should be of type 'string'. I assume this is a property that hasn't been coded yet. Will it been implemented soon?

**Comment by Alberthaff** [comment]
Hello @RozennK.
Thank you for reporting the issue. There was a small bug in the papaparse-interface.
The issue should be resolved as of version 2.0.4. :-)
