### ISSUE TITLE
Incorrect parsing for data cells separated by comma and double quotes with space in between

### ISSUE THREAD

**Issue by samirjoglekar1234** [Alberthaff/ngx-papaparse#14]
[sample.zip](https://github.com/Alberthaff/ngx-papaparse/files/1621653/sample.zip)
The attached file contains characters like this:

, "

The parser incorrectly parses and creates more data cells than headers.

**Comment by Alberthaff** [comment]
Hi.

This is most likely an issue within Papa Parse itself, since this library is just a wrapper.
All CSV-reading is done by Papa Parse.

Please create an issue here:
https://github.com/mholt/PapaParse/issues

**Comment by samirjoglekar1234** [comment]
Thanks for the clarification.
