### ISSUE TITLE
Metadata version mismatch in module?

### ISSUE THREAD

**Issue by RozennK** [Alberthaff/ngx-papaparse#15]
I've been getting this error, possibly since a version change:

ERROR in Error: Metadata version mismatch for module /my/directories/node_modules/ngx-papaparse/ngx-papaparse.d.ts, found version 4, expected 3, resolving symbol RandomModule in /my/directories/src/app/modules/features/random/random.module.ts, resolving symbol RandomModule in /my/directories/src/app/modules/features/random/random.module.ts

The error disappears if I replace '"version":4' in ngx-papaparse.metadata.json with '"version":3'.

I'm not sure it's a problem with the module but I'm not really seeing what the error would be on my end either.

**Comment by Alberthaff** [comment]
Which version of Angular are you using?

If you are using NG <5, please use version 1.x: https://github.com/Alberthaff/ngx-papaparse/tree/v1

**Comment by RozennK** [comment]
I am using Angular 4, and that seems to be it. Thank you!

**Comment by Alberthaff** [comment]
You're welcome.
