### ISSUE TITLE
Config interface for unparse method should different from config for parse method

### ISSUE THREAD

**Issue by mgoku** [Alberthaff/ngx-papaparse#17]
As documented at https://www.papaparse.com/docs#json-to-csv, config for `parse` method is different from config for `unparse` method.

For example, `unparse` config has `quotes` option, which does not exist in `parse` config.

This library, use `PapaParseConfig` interface for both `parse` and `unparse` method. This cause a compile error when I try to pass `{quotes: true}` as config parameter for unparse.

```
this.papa.unparse(data, {quotes: true});
```

I think we can fix this problem by providing different inteface for `parse` and `unparse`.

**Comment by Alberthaff** [comment]
Hi. 
Thank you for reporting the issue. You are right. I will add a new interface for unparse ASAP.

**Comment by mgoku** [comment]
Nice, thank you

**Comment by Alberthaff** [comment]
The interface is called `PapaUnparseConfig`. It is available as of version 2.1.0.

**Comment by mgoku** [comment]
Thank you
