### ISSUE TITLE
Angular 6 Support

### ISSUE THREAD

**Issue by remeezp** [alberthaff/ngx-papaparse#19]
Hi, will you be upgrading to angular 6?

**Comment by alberthaff** [comment]
Yes, however, it is still under development.
I'll try to finish it during this weekend.

**Comment by alberthaff** [comment]
Sorry for the delay. I am almost done with the patch (had some issues i did not expect with switching the compiler to Angular's new official one).
I will most likely be done within a few more days.

I just need to finish the docs for version 3 before releasing the patch on NPM.

**Comment by alberthaff** [comment]
I have uploaded a beta that is compatible with Angular 6. I will upload 3.0.0 stable when the unit tests are ready.

You can install it by running 

```
npm i ngx-papaparse@3.0.0-beta.0
```

The docs are available [here](https://alberthaff.dk/projects/ngx-papaparse/docs/v3). The UI is still WIP. [Feedback is greatly appreciated](https://github.com/alberthaff/ngx-papaparse/issues/22).

Following changes may be breaking, if you are upgrading an existing project:
- Renamed `PapaParseService` to `Papa`.
- Renamed `BAD_DELIMITERS`, `RECORD_SEP`, `UNIT_SEP` and `WORKERS_SUPPORTED` to `badDelimiters`, `recordSeperator`, `unitSeperator` and `workersSupported`.
- Renamed `workerScriptPath` to `scriptPath` in the global configuration.

**Comment by alberthaff** [comment]
I have uploaded ngx-papaparse@3.0.0. It is available on [npm](https://www.npmjs.com/package/ngx-papaparse).
