### ISSUE TITLE
Error when running ng serve or ng build with papaparse@4.5 or never

### ISSUE THREAD

**Issue by remeezp** [alberthaff/ngx-papaparse#26]
Hi,

I am getting the following error when running the mentioned commands:

> ERROR in ./node_modules/papaparse/papaparse.min.js
> Module not found: Error: Can't resolve 'stream' in 'C:\development\workbench\node_modules\papaparse'

**Comment by alberthaff** [comment]
Hi. Which branch are you trying to compile?

**Comment by DaviR87** [comment]
Same here

**@angular/cli**: "6.0.7"
**ngx-papaparse**: "3.0.0-beta.0"

**Comment by DaviR87** [comment]
@alberthaff It works now. Thank you for this temp fix!

**Comment by remeezp** [comment]
@alberthaff, thanks very much it's working.

**Comment by rickyrojas1** [comment]
still getting this error with the latest ngx-papaparse....is there any fix?

**Comment by brannon-darby** [comment]
works for me with the temp fix

https://github.com/alberthaff/ngx-papaparse/issues/26#issuecomment-394872523

**Comment by rickyrojas1** [comment]
I was able to get it after restarting vsCode. Thank you!

**Comment by alberthaff** [comment]
@mgoku Yes. It does not seem like something that will be fixed in the near future, so I will change the dependency to `papaparse@~4.4.0` in the next release.

**Comment by alberthaff** [comment]
The problem seems to have been solved as of papaparse@4.6.2.

Can anybody confirm this, by running following in a project where you are using ngx-papaparse?

```
npm i ngx-papaparse@3.0.1 papaparse@4.6.2
ng serve
```

If you are not receiving any errors, the problem has been solved.
