### ISSUE TITLE
complete callback has wrong signature

### ISSUE THREAD

**Issue by or1can** [alberthaff/ngx-papaparse#28]
**Describe the bug**

The complete callback has the following signature is PapaParseConfig

`complete?: (results: PapaParseResult, parser: PapaParseParser) => void;`

but Papa Parse actually calls with the results and a File object if parsing a local file.

This causes type errors when using this callback and the only workaround I found was to define a complete callback specifying the type of the second argument as `any`, e.g.

`complete: (results, file: any) => {}`

The signature for `step` looks correct, I'm not sure about `chunk`.

**Comment by alberthaff** [comment]
Hi.
Thanks for the error-report. 
Are you using ngx-papaparse 2.x or 3.x?

**Comment by or1can** [comment]
I'm using 3.0.0-beta.0

**Comment by alberthaff** [comment]
Thanks. I'll take a look at it. :-)

**Comment by alberthaff** [comment]
I have changed the interface to:

`complete?: (results: PapaParseResult, file?: File) => void;`.

The change will be included in the next release.
