### ISSUE TITLE
Angular 7 Update

### ISSUE THREAD

**Issue by pantonis** [alberthaff/ngx-papaparse#30]
Can you please update to Angular 7

**Comment by alberthaff** [comment]
Yes I will upgrade to Angular 7, but I am a little pressed for time at the moment.
Are there any issues using ngx-papaparse@3.0.0 with NG 7?

**Comment by rayzru** [comment]
AFAIK, using `ngx-papaparse` for 2 weeks causes no issues at all at NG7. It's just throwing those warnings.

```
npm WARN ngx-papaparse@3.0.0 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-papaparse@3.0.0 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
```

Just tested it with 7.0.4.

**Comment by shyamal890** [comment]
+1

**Comment by alberthaff** [comment]
The warning should be gone, as of version 3.0.1
