### ISSUE TITLE
transformHeader

### ISSUE THREAD

**Issue by median-man** [alberthaff/ngx-papaparse#31]
**Feature Request**

I would like to see the `transformHeader` configuration property supported by this component. This feature is useful for trimming off pesky white space between commas in the header row, in addition to formatting headers in other ways or performing fuzzy matching on them before getting the output back from Papa.

See the [PapaParse docs](https://www.papaparse.com/docs#config) for a complete description of `config.transformHeader`.

**Expected behavior**

I would like to provide a function to configuration which accepts the header as an argument and returns a string to be used in place of that header so that I can trim white space, performing matching, etc. with the headers. This function should work precisely as `config.transformHeader` works in PapaParse.

**Comment by alberthaff** [comment]
Great idea. I will look into adding this.

However, I have to check, in which version of papaparse this feature was introduced, since i think issue #26 is still a problem.

**Comment by TeXnicians** [comment]
I need this feature too. Is it added in 4.0?

**Comment by alberthaff** [comment]
It is still only available in the Papa Parse beta.
ngx-papaparse 4 will be released when papaparse 5 is ready.

**Comment by alberthaff** [comment]
Closing this, in favor of #39. A beta of the new version is available.
