### ISSUE TITLE
Missing export of PapaUnparseConfig type

### ISSUE THREAD

**Issue by hlovdal** [alberthaff/ngx-papaparse#33]
**Describe the bug**

The exported class `Papa` has a method with signature
```typescript
    unparse(data: any, config?: PapaUnparseConfig): string;
```
however the `PapaUnparseConfig` type is not exported from ngx-papaparse, making it impossible to pass a typed variable as parameter to `unparse`.

This parameter used to be of type PapaParseConfig which also used to be exported.

**To Reproduce**

```typescript
import { Papa, PapaUnparseConfig } from 'ngx-papaparse'; // [ts] Module '".../ngx-papaparse"' has no exported member 'PapaUnparseConfig'. [2305]
...
class SomeClass {

  exportConfig: PapaUnparseConfig = {
    delimiter: ';',
    header: true,
    skipEmptyLines: true,
    newline: '\r\n',
    worker: true,
  };

...

  someFunction(...) {
    ...
    return this.papaParse.unparse(
      {
        fields: MY_CSV_COLUMNS,
        data: mydata,
      },
      this.exportConfig);
  }
```

**Expected behavior**

`ngx-papaparse` should export all types that the `Papa` class depends on.

**Comment by alberthaff** [comment]
Somehow i had managed to remove all the interfaces from `public_api.ts`. 
The issue should be solved as of version 3.0.2 :-)
