### ISSUE TITLE
Add support for delimitersToGuess

### ISSUE THREAD

**Issue by nosovk** [alberthaff/ngx-papaparse#38]
Currently in updated Papa Parse version there is a new options parameter.
[```delimitersToGuess: [',', '\t', '|', ';', Papa.RECORD_SEP, Papa.UNIT_SEP]```](https://www.papaparse.com/docs#config)
Could you please update PapaParse and config description to expose new settings?

**Comment by alberthaff** [comment]
Sure. I'll take a look at it. :-)

**Comment by alberthaff** [comment]
Unfortunately, this feature is only available in the beta version of Papa Parse. I will add this to the 4.x todo.

**Comment by alberthaff** [comment]
Closing this, in favor of #39. A beta of the new version is available.
