### ISSUE TITLE
Add support for papaparse 5.0.0

### ISSUE THREAD

**Issue by awe123343** [alberthaff/ngx-papaparse#39]
Papa parse 5.0.0 is out. Some features like transformHeader is really useful, do you mind add support for the latest version?

**Comment by alberthaff** [comment]
Great. I will look into releasing an update asap.

**Comment by alberthaff** [comment]
A beta is available. Any feedback is appreciated.

`npm i ngx-papaparse@4.0.0-beta.1`

TODO before release:
- [x] Add all new features
- [ ] Test new callbacks (parse config)
- [ ] Update 4.0 docs

**Comment by alberthaff** [comment]
ngx-papaparse 4.0 has been released https://npmjs.com/package/ngx-papaparse
