### ISSUE TITLE
Please update for Angular 8 

### ISSUE THREAD

**Issue by ggoodfrd** [alberthaff/ngx-papaparse#40]
**Describe the bug**

I'm getting this error while installing packages on my app that's recently been updated to Angular 8:  

> npm WARN ngx-papaparse@3.0.2 requires a peer of @angular/common@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.

**To Reproduce**

Install current ngx-papaparse on a new or upgraded Angular 8 project
> npm install ngx-papaparse --save

**Expected behavior**

No warnings or errors

**Software and platform**

 - OS: Windows 10
 - Browser: Chrome
 - Version: 74.0.3729.169
 - Angular version: 8.0.0 / 8.0.2
 - Angular CLI version: 8.0.3
 - Node version: 12.4.0

**Comment by alberthaff** [comment]
Thanks. I have just released version 3.0.3, which should solve this.

**Comment by ggoodfrd** [comment]
Thanks for the quick response! All set. Greatly appreciated :)
