### ISSUE TITLE
Uncaught ReferenceError: webpackJsonp is not defined

### ISSUE THREAD

**Issue by sayeko** [Alberthaff/ngx-papaparse#6]
it happen when I use worker property.

**Comment by Alberthaff** [comment]
Hi @sayeko.

Thanks for reporting the issue. 
I have identified the problem and will release a new version with a fix ASAP.

Best regards,
Albert

**Comment by sayeko** [comment]
@Alberthaff  10x.
please let me know in this thread if the bug fixed.

**Comment by Alberthaff** [comment]
The issue has been solved as of version 2.0.0.
Please note that version 2.0.0 requires Angular 5.
