### ISSUE TITLE
Please update for Angular 9

### ISSUE THREAD

**Issue by renemadsen** [alberthaff/ngx-papaparse#60]
**Describe the bug**

I'm getting this warning while installing packages on my app that's recently been updated to Angular 9:

Entry point 'ngx-papaparse' contains deep imports into '.../node_modules/papaparse/papaparse.min.js'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

**To Reproduce**

Install current ngx-papaparse on a new or upgraded Angular 9 project

**Expected behavior**

No warnings or errors

**Software and platform**

 - OS: Ubuntu 19.10
 - Browser: any
 - Version: any
 - Angular version: 9.1.1
 - Angular CLI version: 9.1.1
 - Node version: 12.16.2

**Additional context**

**Comment by alberthaff** [comment]
A fix has been pushed - it will be included in the v5-release.

**Comment by Gemorroj** [comment]
can't install using yarn
