### ISSUE TITLE
Angular10 reports a CommonJS warning for PapaParse

### ISSUE THREAD

**Issue by sserdyuk** [alberthaff/ngx-papaparse#65]
Angular produces this message at the build. I can temporarily suppress it by adding an exception to angular.json file, but it would be nice to have the library properly packaged. Here's a link to Angular's documentation on CommonJS related issues: https://angular.io/guide/build#configuring-commonjs-dependencies

`WARNING in /home/sergei/Projects/Angular/revenue-matters/node_modules/ngx-papaparse/__ivy_ngcc__/fesm2015/ngx-papaparse.js depends on 'papaparse/papaparse.min.js'. CommonJS or AMD dependencies can cause optimization bailouts.`

**Comment by Amanpreet21** [comment]
I am adding this :
 "allowedCommonJsDependencies": [
        "lodash"
     ]
to angular.json but not able to suppress the warning.

**Comment by alberthaff** [comment]
I have just release V5. 
This is a problem with Papa Parse being a Common JS library. However, as @Amanpreet21 pointed out, you can disable the warning.
More information here: https://alberthaff.dk/projects/ngx-papaparse/docs/v5/installation/angular-10-or-later
