### ISSUE TITLE
Angular 10 - unable to install

### ISSUE THREAD

**Issue by ezpzlmnsqzy2** [alberthaff/ngx-papaparse#68]
I tried installing with the following command from the readme instructions:
`npm install ngx-papaparse@5 --save`
However I got the following error:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ngx-papaparse@5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

So, I went down to 4, which installs without any issue:
`npm install ngx-papaparse@4 --save`

However, I cannot actually use the library in my project (in app.module.ts):
`import { PapaParseModule } from 'ngx-papaparse';`
Results in the this error:
`Module '"../../node_modules/ngx-papaparse/ngx-papaparse"' has no exported member 'PapaParseModule'.ts(2305)`

**Comment by alberthaff** [comment]
Hi.

Version 5 was not release yet. However, I have just release version 5. Please try again.
