### ISSUE TITLE
An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by carlosnp** [alberthaff/ngx-papaparse#84]
**Describe the bug**

The compilation error occurs because there are some lines that typescript detects:
An accessor cannot be declared in an ambient context.

The errors are in node_modules/ngx-papaparse/lib/papa.de.ts, in the lines:
- 32: 9 - TS1086 error
- 37: 9 - TS1086 error
- 41: 9 - error TS1086
- 46: 9 - TS1086 error

**To Reproduce**

The error occurs when compiling the angular project

ng serve

**Expected behavior**

hope it compiles correctly, no errors

**Software and platform**

 - OS: Ubuntu 20.04
 - Browser: Google Chrome  91.0.4472.114 
 - Version: 5
 - Angular version: 12
 - Angular CLI version: 12.0.4
 - Node version:  14.17.2

**Additional context**

Although it is not a good practice, the problem can be solved by adding to the tsconfig.ts file, in compilerOptions the line: "skipLibCheck": true, and now, TypeScript allows me to use the library as long as I do not use the incompatible parts or with

**Comment by alberthaff** [comment]
Thanks for reporting this!
I'm leaving for vacation tomorrow, so I won't have time to look at this until I'm back.
